use std::collections::{HashMap, HashSet};

pub fn get_first() -> HashMap<String, HashSet<String>> {
    let mut first = HashMap::new();
    first.insert("DTYPE".to_string(), vec!["TypeChar", "TypeList", "TypeFloat", "TypeArray", "TypeBoolean", "TypeInt", "TypeStruct"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FIELD".to_string(), vec!["TypeStruct", "TypeArray", "TypeList", "TypeInt", "TypeBoolean", "TypeFloat", "TypeChar"].into_iter().map(|s| s.to_string()).collect());
    first.insert("RETTYPE".to_string(), vec!["TypeArray", "TypeList", "TypeChar", "TypeBoolean", "TypeInt", "TypeVoid", "TypeFloat", "TypeStruct"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGOR_TAIL".to_string(), vec!["ε", "OrOr"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PARAMS".to_string(), vec!["TypeInt", "ε", "TypeFloat", "TypeList", "TypeStruct", "TypeBoolean", "TypeArray", "TypeChar"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ITEM".to_string(), vec!["While", "TypeFloat", "TypeBoolean", "CharLit", "LParen", "StringLit", "FloatLit", "Ampersand", "TypeInt", "SIntLit", "TypeList", "TypeArray", "If", "Continue", "Null", "BoolLit", "TypeStruct", "IDENT", "TypeChar", "Tilde", "Minus", "Break", "Func", "For", "ModuleStart", "Return"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODITEM_LIST".to_string(), vec!["TypeInt", "TypeChar", "TypeList", "Return", "TypeBoolean", "Null", "If", "Continue", "Let", "IDENT", "Ampersand", "SIntLit", "For", "Minus", "FloatLit", "LParen", "While", "BoolLit", "StringLit", "Break", "Pub", "TypeStruct", "CharLit", "TypeFloat", "TypeArray", "Tilde", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("UNOP".to_string(), vec!["Tilde", "Ampersand", "Minus"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ITEM_LIST".to_string(), vec!["IDENT", "SIntLit", "Break", "LParen", "BoolLit", "FloatLit", "TypeBoolean", "Continue", "TypeInt", "TypeArray", "TypeStruct", "TypeChar", "ε", "For", "Ampersand", "If", "Return", "Tilde", "TypeFloat", "Func", "TypeList", "ModuleStart", "Minus", "CharLit", "StringLit", "Null", "While"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGAND".to_string(), vec!["Minus", "BoolLit", "Ampersand", "StringLit", "FloatLit", "LParen", "Tilde", "Null", "SIntLit", "IDENT", "CharLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ARGS".to_string(), vec!["BoolLit", "IDENT", "LParen", "CharLit", "Null", "ε", "Ampersand", "Minus", "Tilde", "SIntLit", "StringLit", "FloatLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("STMT".to_string(), vec!["Continue", "TypeArray", "Return", "Tilde", "TypeStruct", "Ampersand", "For", "TypeInt", "CharLit", "Null", "If", "IDENT", "TypeChar", "LParen", "Minus", "TypeList", "Break", "StringLit", "FloatLit", "While", "SIntLit", "BoolLit", "TypeBoolean", "TypeFloat"].into_iter().map(|s| s.to_string()).collect());
    first.insert("EXPR".to_string(), vec!["StringLit", "CharLit", "BoolLit", "Ampersand", "FloatLit", "SIntLit", "Tilde", "Null", "IDENT", "LParen", "Minus"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PRIMARY".to_string(), vec!["IDENT", "FloatLit", "CharLit", "BoolLit", "Null", "SIntLit", "LParen", "StringLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PUBOPT".to_string(), vec!["ε", "Pub"].into_iter().map(|s| s.to_string()).collect());
    first.insert("POSTFIX_TAIL".to_string(), vec!["As", "Dot", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ASSIGNOP".to_string(), vec!["PlusEquals", "AmpersandEquals", "Equals", "SlashEquals", "PercentEquals", "CaretEquals", "MinusEquals", "StarEquals", "PipeEquals"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PARAMS_TAIL".to_string(), vec!["Comma", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ARGS_TAIL".to_string(), vec!["Comma", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FUNCDEF".to_string(), vec!["Func"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MUL".to_string(), vec!["Ampersand", "Null", "FloatLit", "StringLit", "BoolLit", "Minus", "Tilde", "IDENT", "LParen", "CharLit", "SIntLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODFUNCDEF".to_string(), vec!["ε", "Pub"].into_iter().map(|s| s.to_string()).collect());
    first.insert("BLK".to_string(), vec!["LBrace"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CMP".to_string(), vec!["Tilde", "Ampersand", "FloatLit", "BoolLit", "LParen", "CharLit", "Minus", "Null", "StringLit", "SIntLit", "IDENT"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ADD_TAIL".to_string(), vec!["Plus", "Minus", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LVALUE_TAIL".to_string(), vec!["ε", "Dot"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LVALUE".to_string(), vec!["IDENT"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODDECL".to_string(), vec!["Let"].into_iter().map(|s| s.to_string()).collect());
    first.insert("POSTFIX".to_string(), vec!["FloatLit", "SIntLit", "BoolLit", "IDENT", "LParen", "StringLit", "Null", "CharLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MUL_TAIL".to_string(), vec!["Percent", "ε", "Star", "Slash"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CALL_OPT".to_string(), vec!["LParen", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODITEM".to_string(), vec!["Continue", "SIntLit", "For", "If", "Return", "IDENT", "TypeArray", "Minus", "Tilde", "Pub", "TypeFloat", "CharLit", "FloatLit", "Ampersand", "Break", "Null", "TypeInt", "TypeBoolean", "While", "LParen", "BoolLit", "TypeChar", "ε", "TypeStruct", "Let", "TypeList", "StringLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PARAM".to_string(), vec!["TypeInt", "TypeStruct", "TypeArray", "TypeList", "TypeFloat", "TypeBoolean", "TypeChar"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ADD".to_string(), vec!["LParen", "FloatLit", "BoolLit", "Null", "CharLit", "Tilde", "StringLit", "Minus", "SIntLit", "Ampersand", "IDENT"].into_iter().map(|s| s.to_string()).collect());
    first.insert("STMTS".to_string(), vec!["IDENT", "TypeList", "ε", "Ampersand", "TypeChar", "Continue", "StringLit", "Break", "While", "TypeInt", "TypeBoolean", "Return", "TypeFloat", "For", "TypeArray", "Tilde", "CharLit", "If", "TypeStruct", "LParen", "SIntLit", "BoolLit", "Null", "Minus", "FloatLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PRIMARY_TAIL".to_string(), vec!["LParen", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODULE".to_string(), vec!["ModuleStart"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ELSEPART".to_string(), vec!["ε", "Else"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODSTMT".to_string(), vec!["TypeChar", "LParen", "FloatLit", "SIntLit", "BoolLit", "Minus", "TypeInt", "TypeFloat", "Tilde", "Continue", "Break", "For", "Null", "Return", "CharLit", "While", "TypeStruct", "TypeList", "TypeArray", "StringLit", "If", "TypeBoolean", "Ampersand", "IDENT"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FIELDS".to_string(), vec!["TypeInt", "ε", "TypeBoolean", "TypeArray", "TypeChar", "TypeStruct", "TypeList", "TypeFloat"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CMPOP".to_string(), vec!["TildeEquals", "GreaterEquals", "LessEquals", "Less", "Greater", "EqualsEquals"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGOR".to_string(), vec!["SIntLit", "LParen", "FloatLit", "Minus", "Tilde", "Null", "StringLit", "IDENT", "CharLit", "BoolLit", "Ampersand"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PRGM".to_string(), vec!["Start"].into_iter().map(|s| s.to_string()).collect());
    first.insert("DECL".to_string(), vec!["TypeFloat", "TypeBoolean", "TypeList", "TypeChar", "TypeArray", "TypeStruct", "TypeInt"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGAND_TAIL".to_string(), vec!["ε", "AndAnd"].into_iter().map(|s| s.to_string()).collect());
    first.insert("STRUCTDEF".to_string(), vec!["TypeStruct"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CMP_TAIL".to_string(), vec!["TildeEquals", "Less", "GreaterEquals", "EqualsEquals", "ε", "LessEquals", "Greater"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ASSIGN".to_string(), vec!["IDENT"].into_iter().map(|s| s.to_string()).collect());
    first.insert("UNARY".to_string(), vec!["Ampersand", "Tilde", "StringLit", "FloatLit", "BoolLit", "SIntLit", "Minus", "Null", "CharLit", "IDENT", "LParen"].into_iter().map(|s| s.to_string()).collect());
    first.insert("DECLTAIL".to_string(), vec!["Equals", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FUNC_END".to_string(), vec!["ε", "EndL"].into_iter().map(|s| s.to_string()).collect());
    first
}

pub fn get_follow() -> HashMap<String, HashSet<String>> {
    let mut follow = HashMap::new();
    follow.insert("UNARY".to_string(), vec!["ε", "Percent", "Slash", "Star"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FUNC_END".to_string(), vec!["ModuleStart", "LParen", "TypeList", "TypeFloat", "ε", "If", "TypeStruct", "Break", "Return", "StringLit", "Ampersand", "Continue", "TypeChar", "FloatLit", "Null", "While", "SIntLit", "Func", "TypeInt", "IDENT", "TypeArray", "TypeBoolean", "Minus", "For", "Tilde", "CharLit", "BoolLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("STMTS".to_string(), vec!["RBrace"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ASSIGNOP".to_string(), vec!["Minus", "LParen", "Null", "Ampersand", "CharLit", "FloatLit", "IDENT", "StringLit", "Tilde", "BoolLit", "SIntLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGAND_TAIL".to_string(), vec!["ε", "OrOr"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ITEM_LIST".to_string(), vec!["End"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CMP".to_string(), vec!["AndAnd", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ITEM".to_string(), vec!["Minus", "CharLit", "Null", "SIntLit", "StringLit", "TypeList", "IDENT", "While", "FloatLit", "ModuleStart", "If", "TypeChar", "TypeStruct", "Break", "Ampersand", "LParen", "Continue", "For", "TypeArray", "BoolLit", "ε", "TypeFloat", "TypeBoolean", "Func", "TypeInt", "Return", "Tilde"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ADD_TAIL".to_string(), vec!["GreaterEquals", "LessEquals", "Greater", "ε", "EqualsEquals", "Less", "TildeEquals"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("STRUCTDEF".to_string(), vec!["For", "TypeList", "Continue", "TypeInt", "Return", "If", "Ampersand", "Minus", "CharLit", "TypeArray", "While", "Null", "LParen", "SIntLit", "Break", "TypeStruct", "ModuleStart", "TypeFloat", "TypeChar", "IDENT", "ε", "FloatLit", "BoolLit", "TypeBoolean", "Func", "Tilde", "StringLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PRIMARY".to_string(), vec!["As", "Dot", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CMP_TAIL".to_string(), vec!["ε", "AndAnd"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODSTMT".to_string(), vec!["Pub", "CharLit", "IDENT", "Null", "TypeFloat", "FloatLit", "Let", "Minus", "StringLit", "TypeList", "If", "Ampersand", "BoolLit", "TypeInt", "Return", "ε", "Continue", "SIntLit", "TypeArray", "TypeChar", "Break", "LParen", "TypeStruct", "While", "TypeBoolean", "Tilde", "For"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FIELDS".to_string(), vec!["RBrace"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODITEM_LIST".to_string(), vec!["ModuleEnd"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ADD".to_string(), vec!["EqualsEquals", "Less", "LessEquals", "Greater", "ε", "TildeEquals", "GreaterEquals"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MUL".to_string(), vec!["ε", "Minus", "Plus"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGOR".to_string(), vec!["RParen", "ε", "Comma", "EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGAND".to_string(), vec!["ε", "OrOr"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CALL_OPT".to_string(), vec!["ε", "As", "Dot"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGOR_TAIL".to_string(), vec!["EndL", "RParen", "Comma", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FUNCDEF".to_string(), vec!["ε", "EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MUL_TAIL".to_string(), vec!["ε", "Minus", "Plus"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ARGS".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("STMT".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("DTYPE".to_string(), vec!["LBrace", "As", "Equals", "IDENT", "ε", "Dot"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ARGS_TAIL".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LVALUE_TAIL".to_string(), vec!["SlashEquals", "StarEquals", "CaretEquals", "AmpersandEquals", "PlusEquals", "PercentEquals", "MinusEquals", "Equals", "PipeEquals"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODITEM".to_string(), vec!["Ampersand", "StringLit", "TypeStruct", "CharLit", "Pub", "TypeBoolean", "Minus", "IDENT", "Break", "TypeList", "If", "BoolLit", "Null", "Tilde", "TypeChar", "Return", "For", "TypeFloat", "TypeInt", "FloatLit", "LParen", "ε", "Let", "Continue", "While", "SIntLit", "TypeArray"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ELSEPART".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("EXPR".to_string(), vec!["ε", "RParen", "EndL", "Comma"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("RETTYPE".to_string(), vec!["LBrace"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("DECLTAIL".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODFUNCDEF".to_string(), vec!["TypeChar", "Break", "Ampersand", "CharLit", "TypeFloat", "StringLit", "IDENT", "TypeStruct", "Tilde", "FloatLit", "LParen", "While", "SIntLit", "Null", "TypeBoolean", "Minus", "Return", "TypeList", "Let", "Continue", "If", "For", "BoolLit", "Pub", "ε", "TypeInt", "TypeArray"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FIELD".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PARAMS".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("BLK".to_string(), vec!["Else", "Break", "LParen", "For", "While", "TypeChar", "SIntLit", "TypeInt", "Pub", "Let", "EndL", "If", "Tilde", "TypeArray", "Null", "Continue", "CharLit", "StringLit", "Minus", "IDENT", "Ampersand", "BoolLit", "ε", "TypeFloat", "TypeStruct", "TypeBoolean", "Return", "TypeList", "FloatLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PRIMARY_TAIL".to_string(), vec!["As", "Dot", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PRGM".to_string(), vec!["$"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CMPOP".to_string(), vec!["SIntLit", "Ampersand", "BoolLit", "IDENT", "Null", "CharLit", "Minus", "FloatLit", "Tilde", "LParen", "StringLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODULE".to_string(), vec!["Minus", "StringLit", "TypeInt", "Func", "For", "IDENT", "Continue", "ModuleStart", "ε", "TypeBoolean", "CharLit", "Return", "BoolLit", "Break", "LParen", "SIntLit", "TypeChar", "Ampersand", "TypeStruct", "Tilde", "TypeArray", "Null", "TypeFloat", "TypeList", "While", "FloatLit", "If"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LVALUE".to_string(), vec!["CaretEquals", "MinusEquals", "PipeEquals", "AmpersandEquals", "Equals", "PlusEquals", "PercentEquals", "StarEquals", "SlashEquals"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("POSTFIX".to_string(), vec!["Percent", "ε", "Star", "Slash"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("POSTFIX_TAIL".to_string(), vec!["Percent", "Star", "ε", "Slash"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ASSIGN".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("DECL".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("UNOP".to_string(), vec!["Ampersand", "SIntLit", "FloatLit", "Minus", "BoolLit", "LParen", "CharLit", "StringLit", "Tilde", "IDENT", "Null"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PARAM".to_string(), vec!["Comma", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PUBOPT".to_string(), vec!["Fn"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODDECL".to_string(), vec!["TypeInt", "StringLit", "Break", "While", "Tilde", "Pub", "Let", "SIntLit", "TypeArray", "TypeBoolean", "If", "ε", "CharLit", "TypeStruct", "Return", "IDENT", "For", "Ampersand", "LParen", "Continue", "TypeChar", "TypeList", "Null", "FloatLit", "Minus", "BoolLit", "TypeFloat"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PARAMS_TAIL".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow
}
