use std::collections::{HashMap, HashSet};

pub fn get_first() -> HashMap<String, HashSet<String>> {
    let mut first = HashMap::new();
    first.insert("MODITEM_LIST".to_string(), vec!["Minus", "ε", "StringLit", "Null", "Tilde", "Let", "For", "If", "TypeArray", "FloatLit", "While", "TypeInt", "CharLit", "Ampersand", "TypeChar", "Continue", "TypeStruct", "BoolLit", "TypeList", "Pub", "IDENT", "Break", "SIntLit", "LParen", "TypeFloat", "TypeBoolean", "Return"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PUBOPT".to_string(), vec!["ε", "Pub"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGAND".to_string(), vec!["Null", "StringLit", "IDENT", "LParen", "CharLit", "Tilde", "Ampersand", "BoolLit", "SIntLit", "FloatLit", "Minus"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODSTMT".to_string(), vec!["Tilde", "BoolLit", "Ampersand", "If", "StringLit", "TypeStruct", "TypeBoolean", "Minus", "IDENT", "TypeArray", "SIntLit", "Continue", "TypeList", "CharLit", "Return", "For", "FloatLit", "While", "TypeFloat", "TypeChar", "Break", "TypeInt", "LParen", "Null"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ADD".to_string(), vec!["Tilde", "BoolLit", "FloatLit", "Null", "CharLit", "IDENT", "Minus", "LParen", "StringLit", "SIntLit", "Ampersand"].into_iter().map(|s| s.to_string()).collect());
    first.insert("STMT".to_string(), vec!["TypeChar", "If", "BoolLit", "FloatLit", "LParen", "TypeList", "Ampersand", "While", "TypeInt", "Return", "For", "TypeBoolean", "Tilde", "Break", "TypeStruct", "Null", "StringLit", "CharLit", "Minus", "TypeFloat", "IDENT", "TypeArray", "SIntLit", "Continue"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ARGS_TAIL".to_string(), vec!["Comma", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("BLK".to_string(), vec!["LBrace"].into_iter().map(|s| s.to_string()).collect());
    first.insert("EXPR".to_string(), vec!["BoolLit", "Null", "LParen", "FloatLit", "StringLit", "CharLit", "SIntLit", "Ampersand", "Tilde", "Minus", "IDENT"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODITEM".to_string(), vec!["SIntLit", "FloatLit", "LParen", "Break", "TypeList", "TypeStruct", "TypeChar", "TypeArray", "For", "Pub", "TypeInt", "Continue", "While", "Return", "TypeFloat", "CharLit", "Null", "ε", "Minus", "StringLit", "Let", "IDENT", "BoolLit", "Tilde", "TypeBoolean", "Ampersand", "If"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FUNC_END".to_string(), vec!["EndL", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("RETTYPE".to_string(), vec!["TypeBoolean", "TypeArray", "TypeInt", "TypeStruct", "TypeChar", "TypeVoid", "TypeList", "TypeFloat"].into_iter().map(|s| s.to_string()).collect());
    first.insert("STMTS".to_string(), vec!["TypeChar", "FloatLit", "Tilde", "Null", "Return", "TypeStruct", "Ampersand", "StringLit", "IDENT", "SIntLit", "Minus", "If", "TypeInt", "ε", "CharLit", "BoolLit", "For", "Break", "LParen", "While", "Continue", "TypeFloat", "TypeBoolean", "TypeArray", "TypeList"].into_iter().map(|s| s.to_string()).collect());
    first.insert("POSTFIX".to_string(), vec!["LParen", "FloatLit", "IDENT", "Null", "StringLit", "SIntLit", "CharLit", "BoolLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("DTYPE".to_string(), vec!["TypeBoolean", "TypeList", "TypeStruct", "TypeArray", "TypeInt", "TypeFloat", "TypeChar"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PRIMARY_TAIL".to_string(), vec!["LParen", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ITEM".to_string(), vec!["Null", "Return", "Func", "Continue", "If", "For", "TypeStruct", "LParen", "TypeBoolean", "TypeFloat", "While", "Ampersand", "FloatLit", "TypeInt", "StringLit", "CharLit", "TypeArray", "Minus", "BoolLit", "Tilde", "IDENT", "StructKeyword", "Break", "ModuleStart", "TypeChar", "TypeList", "SIntLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODULE".to_string(), vec!["ModuleStart"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGOR_TAIL".to_string(), vec!["OrOr", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ASSIGNOP".to_string(), vec!["AmpersandEquals", "StarEquals", "PercentEquals", "PlusEquals", "CaretEquals", "MinusEquals", "Equals", "SlashEquals", "PipeEquals"].into_iter().map(|s| s.to_string()).collect());
    first.insert("UNARY".to_string(), vec!["BoolLit", "Tilde", "IDENT", "Ampersand", "FloatLit", "Minus", "StringLit", "LParen", "Null", "SIntLit", "CharLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PARAM".to_string(), vec!["TypeBoolean", "TypeInt", "TypeList", "TypeFloat", "TypeArray", "TypeChar", "TypeStruct"].into_iter().map(|s| s.to_string()).collect());
    first.insert("EXPR_TAIL".to_string(), vec!["ε", "CaretEquals", "PlusEquals", "PercentEquals", "StarEquals", "MinusEquals", "Equals", "SlashEquals", "AmpersandEquals", "PipeEquals"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODFUNCDEF".to_string(), vec!["ε", "Pub"].into_iter().map(|s| s.to_string()).collect());
    first.insert("POSTFIX_TAIL".to_string(), vec!["ε", "Dot", "As"].into_iter().map(|s| s.to_string()).collect());
    first.insert("STRUCTDEF".to_string(), vec!["StructKeyword"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CMP_TAIL".to_string(), vec!["Greater", "LessEquals", "EqualsEquals", "ε", "GreaterEquals", "TildeEquals", "Less"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PARAMS".to_string(), vec!["TypeChar", "TypeBoolean", "TypeList", "TypeInt", "TypeFloat", "ε", "TypeArray", "TypeStruct"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PRGM".to_string(), vec!["Start"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MODDECL".to_string(), vec!["Let"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGAND_TAIL".to_string(), vec!["AndAnd", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CALL_OPT".to_string(), vec!["LParen", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ITEM_LIST".to_string(), vec!["BoolLit", "Minus", "Func", "TypeBoolean", "Break", "TypeChar", "LParen", "For", "TypeArray", "Continue", "ModuleStart", "TypeFloat", "TypeList", "Ampersand", "IDENT", "TypeInt", "TypeStruct", "StringLit", "While", "FloatLit", "If", "StructKeyword", "ε", "Return", "Tilde", "CharLit", "Null", "SIntLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("DECL".to_string(), vec!["TypeBoolean", "TypeList", "TypeStruct", "TypeInt", "TypeFloat", "TypeChar", "TypeArray"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ELSEPART".to_string(), vec!["Else", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LOGOR".to_string(), vec!["SIntLit", "Minus", "Ampersand", "Tilde", "LParen", "IDENT", "BoolLit", "StringLit", "FloatLit", "Null", "CharLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ADD_TAIL".to_string(), vec!["Minus", "Plus", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PARAMS_TAIL".to_string(), vec!["ε", "Comma"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LVALUE".to_string(), vec!["IDENT"].into_iter().map(|s| s.to_string()).collect());
    first.insert("PRIMARY".to_string(), vec!["LParen", "IDENT", "StringLit", "Null", "CharLit", "SIntLit", "BoolLit", "FloatLit"].into_iter().map(|s| s.to_string()).collect());
    first.insert("ARGS".to_string(), vec!["StringLit", "ε", "CharLit", "Ampersand", "IDENT", "Minus", "FloatLit", "SIntLit", "LParen", "Null", "BoolLit", "Tilde"].into_iter().map(|s| s.to_string()).collect());
    first.insert("DECLTAIL".to_string(), vec!["Equals", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MUL_TAIL".to_string(), vec!["Percent", "Slash", "Star", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FIELD".to_string(), vec!["TypeBoolean", "TypeFloat", "TypeArray", "TypeChar", "TypeList", "TypeInt", "TypeStruct"].into_iter().map(|s| s.to_string()).collect());
    first.insert("UNOP".to_string(), vec!["Minus", "Tilde", "Ampersand"].into_iter().map(|s| s.to_string()).collect());
    first.insert("MUL".to_string(), vec!["Ampersand", "Tilde", "LParen", "BoolLit", "IDENT", "StringLit", "FloatLit", "SIntLit", "Minus", "CharLit", "Null"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FUNCDEF".to_string(), vec!["Func"].into_iter().map(|s| s.to_string()).collect());
    first.insert("FIELDS".to_string(), vec!["TypeArray", "TypeInt", "TypeFloat", "TypeList", "TypeChar", "TypeBoolean", "ε", "TypeStruct"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CMP".to_string(), vec!["FloatLit", "Minus", "StringLit", "SIntLit", "CharLit", "LParen", "Ampersand", "BoolLit", "Null", "IDENT", "Tilde"].into_iter().map(|s| s.to_string()).collect());
    first.insert("LVALUE_TAIL".to_string(), vec!["Dot", "ε"].into_iter().map(|s| s.to_string()).collect());
    first.insert("CMPOP".to_string(), vec!["LessEquals", "EqualsEquals", "TildeEquals", "GreaterEquals", "Less", "Greater"].into_iter().map(|s| s.to_string()).collect());
    first
}

pub fn get_follow() -> HashMap<String, HashSet<String>> {
    let mut follow = HashMap::new();
    follow.insert("EXPR_TAIL".to_string(), vec!["RParen", "EndL", "Comma", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ITEM".to_string(), vec!["For", "FloatLit", "BoolLit", "IDENT", "TypeInt", "TypeArray", "ε", "TypeStruct", "Break", "Tilde", "StructKeyword", "Null", "If", "TypeFloat", "ModuleStart", "TypeList", "Continue", "Return", "CharLit", "Minus", "StringLit", "While", "SIntLit", "Func", "TypeBoolean", "TypeChar", "Ampersand", "LParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("RETTYPE".to_string(), vec!["LBrace"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("STMT".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("EXPR".to_string(), vec!["Comma", "EndL", "ε", "RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ASSIGNOP".to_string(), vec!["Tilde", "FloatLit", "SIntLit", "Ampersand", "StringLit", "Minus", "BoolLit", "IDENT", "Null", "CharLit", "LParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGAND_TAIL".to_string(), vec!["ε", "OrOr"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ADD".to_string(), vec!["TildeEquals", "GreaterEquals", "Less", "ε", "EqualsEquals", "Greater", "LessEquals"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PARAM".to_string(), vec!["Comma", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODSTMT".to_string(), vec!["BoolLit", "TypeArray", "Pub", "IDENT", "Return", "SIntLit", "TypeBoolean", "FloatLit", "ε", "Break", "While", "TypeFloat", "Minus", "If", "CharLit", "LParen", "Ampersand", "Tilde", "TypeChar", "TypeStruct", "Null", "For", "StringLit", "TypeInt", "TypeList", "Continue", "Let"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("POSTFIX_TAIL".to_string(), vec!["ε", "Slash", "Star", "Percent"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ELSEPART".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("DTYPE".to_string(), vec!["LBrace", "Dot", "IDENT", "Equals", "ε", "As"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODDECL".to_string(), vec!["While", "Continue", "IDENT", "TypeBoolean", "TypeChar", "CharLit", "Null", "If", "TypeStruct", "For", "TypeFloat", "FloatLit", "Minus", "Ampersand", "Break", "TypeList", "BoolLit", "SIntLit", "Let", "ε", "TypeInt", "StringLit", "Pub", "LParen", "Tilde", "TypeArray", "Return"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ARGS".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PRIMARY_TAIL".to_string(), vec!["As", "ε", "Dot"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("DECLTAIL".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ARGS_TAIL".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODITEM_LIST".to_string(), vec!["ModuleEnd"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LVALUE".to_string(), vec![].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGOR_TAIL".to_string(), vec!["AmpersandEquals", "PlusEquals", "PipeEquals", "MinusEquals", "ε", "StarEquals", "CaretEquals", "SlashEquals", "PercentEquals", "Equals"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PARAMS".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CMP_TAIL".to_string(), vec!["ε", "AndAnd"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODFUNCDEF".to_string(), vec!["Pub", "For", "Ampersand", "TypeBoolean", "TypeArray", "Minus", "Continue", "FloatLit", "TypeInt", "Null", "If", "IDENT", "TypeStruct", "StringLit", "Break", "Let", "TypeList", "SIntLit", "ε", "Tilde", "TypeChar", "TypeFloat", "Return", "BoolLit", "While", "LParen", "CharLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FUNCDEF".to_string(), vec!["ε", "EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("BLK".to_string(), vec!["StringLit", "Else", "For", "TypeArray", "Minus", "FloatLit", "Let", "TypeStruct", "TypeFloat", "ε", "LParen", "Break", "Continue", "Return", "CharLit", "Null", "TypeInt", "SIntLit", "TypeBoolean", "TypeChar", "BoolLit", "Tilde", "EndL", "TypeList", "If", "IDENT", "While", "Pub", "Ampersand"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("STMTS".to_string(), vec!["RBrace"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CMP".to_string(), vec!["AndAnd", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PRGM".to_string(), vec!["$"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("UNOP".to_string(), vec!["StringLit", "LParen", "Tilde", "Minus", "IDENT", "SIntLit", "Null", "CharLit", "Ampersand", "FloatLit", "BoolLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("UNARY".to_string(), vec!["ε", "Percent", "Slash", "Star"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LVALUE_TAIL".to_string(), vec![].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MUL".to_string(), vec!["Minus", "ε", "Plus"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGAND".to_string(), vec!["OrOr", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PARAMS_TAIL".to_string(), vec!["RParen"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FIELDS".to_string(), vec!["RBrace"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ITEM_LIST".to_string(), vec!["End"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MUL_TAIL".to_string(), vec!["ε", "Plus", "Minus"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODULE".to_string(), vec!["Null", "LParen", "TypeStruct", "For", "If", "BoolLit", "TypeArray", "ε", "StringLit", "Ampersand", "TypeInt", "Tilde", "SIntLit", "TypeChar", "ModuleStart", "Break", "IDENT", "FloatLit", "Return", "TypeFloat", "Continue", "CharLit", "Func", "TypeList", "TypeBoolean", "Minus", "StructKeyword", "While"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("DECL".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("POSTFIX".to_string(), vec!["ε", "Percent", "Slash", "Star"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("STRUCTDEF".to_string(), vec!["ε", "IDENT", "SIntLit", "TypeStruct", "While", "TypeList", "TypeBoolean", "StructKeyword", "TypeInt", "Null", "Return", "ModuleStart", "Func", "Break", "If", "Ampersand", "Continue", "FloatLit", "CharLit", "For", "TypeFloat", "TypeArray", "Tilde", "BoolLit", "TypeChar", "Minus", "LParen", "StringLit"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FIELD".to_string(), vec!["EndL"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("MODITEM".to_string(), vec!["LParen", "Ampersand", "Break", "While", "ε", "Tilde", "TypeArray", "TypeInt", "TypeFloat", "StringLit", "TypeChar", "If", "Continue", "CharLit", "TypeStruct", "Let", "BoolLit", "Pub", "Null", "IDENT", "For", "Return", "TypeList", "SIntLit", "TypeBoolean", "FloatLit", "Minus"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CALL_OPT".to_string(), vec!["As", "Dot", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("CMPOP".to_string(), vec!["BoolLit", "Minus", "CharLit", "Ampersand", "LParen", "StringLit", "FloatLit", "SIntLit", "Tilde", "IDENT", "Null"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PUBOPT".to_string(), vec!["Fn"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("ADD_TAIL".to_string(), vec!["TildeEquals", "EqualsEquals", "GreaterEquals", "LessEquals", "Less", "ε", "Greater"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("PRIMARY".to_string(), vec!["Dot", "As", "ε"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("LOGOR".to_string(), vec!["ε", "PlusEquals", "SlashEquals", "CaretEquals", "AmpersandEquals", "StarEquals", "PipeEquals", "PercentEquals", "MinusEquals", "Equals"].into_iter().map(|s| s.to_string()).collect());
    follow.insert("FUNC_END".to_string(), vec!["FloatLit", "Minus", "IDENT", "If", "Func", "StructKeyword", "StringLit", "TypeChar", "TypeFloat", "Break", "TypeInt", "Null", "While", "TypeStruct", "Tilde", "TypeArray", "TypeBoolean", "For", "ModuleStart", "SIntLit", "TypeList", "BoolLit", "CharLit", "ε", "LParen", "Return", "Ampersand", "Continue"].into_iter().map(|s| s.to_string()).collect());
    follow
}
